### ISSUE TITLE
Revise Sections 2.1 - 2.1.3 on Documentation

### ISSUE THREAD

**Issue by lex939** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#199]
Objective:

Improve the “Descriptive Part: Domain” section by refining the domain description, providing clearer terminology, and enhancing the explanation of domain-related concepts, including events, actions, behaviors, and function signatures.

Task Description:

This task involves improving the following subsections:

	•	2.1 Domain Description: Provide a clearer and more comprehensive description of the project’s domain.
	•	2.1.1 Domain Rough Sketch: Develop a clearer sketch that outlines the key components of the domain.
	•	2.1.2 Terminology: Define key domain-specific terms with precision.
	•	2.1.3 Domain Terminology in Relation to Domain Rough Sketch: Ensure the terminology and rough sketch are in harmony and provide a solid foundation for the rest of the project.

Implementation:

	1.	Analyze Existing Domain Sketch and Description: Review the current state of the domain description and sketch, identifying areas that need clarification or expansion.
	2.	Refine Terminology: Make sure that all domain-specific terms are well-defined and easy to understand.
	3.	Align Domain Sketch with Terminology: Ensure that the rough sketch and terminology section work together cohesively, providing a complete understanding of the domain.
	4.	Enhance Clarity: Reword and restructure the content for better readability and coherence.

Subtasks:

	1.	Domain Rough Sketch (2.1.1):
	•	Review the rough sketch.
	•	Add any missing components and ensure it gives a clear overview of the domain.
	2.	Terminology (2.1.2):
	•	Clarify and expand definitions for domain-specific terms.
	•	Ensure that the terminology is accessible to all team members and stakeholders.
	3.	Domain Terminology in Relation to Rough Sketch (2.1.3):
	•	Ensure that the domain sketch and terminology align and complement each other.
	•	Make sure that the sketch reflects the terminology accurately and that both are easy to reference during implementation.

Testing and Debugging:

Once updates are made, review the section to confirm:

	•	The domain description provides a clear and complete understanding.
	•	The terminology is well-defined and can be easily referenced by the team.
	•	The domain rough sketch aligns with the terminology and provides a visual aid that enhances understanding.

Deadline:

Complete the improvements for this section by Monday, October 16, 2024, at 11:00 PM (23:00), in alignment with the overall deadline for all 10 sections.

**Comment by Chosen-Juan1** [comment]
rough sketch redo:

Being secure is a feeling that we all wish to have present at all times. Here at the UPRM, we could assume that, along with our fellow students, we remain safe and protected, but that is not always the case. An example of this can be taken from people who leave campus at late hours (like those doing research, those who are working on assignments in a focused environment, or those who finish courses late at night). For these people, once they finish the activities that they were doing, they are met with an empty and dark campus, where anything bad can happen at any time. An option these people have is the campus guard, but relying on calling campus services via phone has always proven to be a hassle. Not only that, should a student wish to report something they saw that was out of the ordinary, there really isn’t a good method of doing so, as our current emergency systems are unorganized and outdated.

	Given these situations, it is noticeable that there is a need for a service that could provide both students and staff ways to communicate dangers that they have observed and methods of calling out for help in a quick and reliable manner. For this reason, we have structured the domain of our application, SafeRUM, around college safety, as we can see an opportunity to provide the people of the UPRM a service that can provide them with a sense of security. With SafeRUM, there is an opportunity to provide quick and easy access to services that can help the people of the UPRM with tools that can help make our campus a safer place. The ability to generate reports can allow users to post detailed forms that communicate a particular situation that can compromise the safety of our students, informationing other users and staff members of something that they should be aware of. In the case of immediate danger, the ability of sending out a quick SOS report can reduce the time it takes to provide aid and safety, without having to run the risk that other alternatives like phone calls entail (like noise in a situation where remaining silent is critical.). Finally, granting the ability to share rumors among users would help those at the UPRM stay informed and on the lookout for potential threats, as well as inform admins of dangers that lurk around campus.

**Comment by Chosen-Juan1** [comment]
The professor noted the old rough sketch as not being rough enough. This hopefully provides a more concrete example.

**Comment by Chosen-Juan1** [comment]
response time and safety portocols should be removed from the terminology, as they labeled as the wrong things

**Comment by Chosen-Juan1** [comment]
For event procedures, (within the terminology), the professor requests specifics. A good way of fixing this would be to provide an example. "An example of such procedures would involve the addition of evacuation routes commonly found on the walls around campus, giving the opportunity to provide high definition maps to our users.

**Comment by Chosen-Juan1** [comment]
@YanehRuiz these are the fixes I could provide to the indicated sections, may I add them?

**Comment by Chosen-Juan1** [comment]
@YanehRuiz these are the modifications that I could come up with based on the professor's feedback. I understand that the documentation is due, however Ill add them after the date so that it may be considered for future milestones.

**Comment by Chosen-Juan1** [comment]
I noticed that I'm still missing a segment, I'll move this one for milestone 3.

**Comment by Chosen-Juan1** [comment]
final version of the rough sketch: 
Being secure is a feeling that we all wish to have present at all times. Here at the UPRM, we could assume that, along with our fellow students, we remain safe and protected, but that is not always the case. An example of this can be taken from people who leave campus at late hours (like those doing research, those who are working on assignments in a focused environment, or those who finish courses late at night). For these people, once they finish the activities that they were doing, they are met with an empty and dark campus, where anything bad can happen at any time. An option these people have is the campus guard, but relying on calling campus services via phone has always proven to be a hassle. Not only that, should a student wish to report something they saw that was out of the ordinary, there really isn’t a good method of doing so, as our current emergency systems are unorganized and outdated.
Due to these situations, it is noticeable that there is a need for a service that could provide both students and staff ways to communicate dangers that they have observed and methods of calling out for help in a quick and reliable manner as given that the National Center for Education Statistics [reported](https://nces.ed.gov/fastfacts/display.asp?id=804) approximately 16.9 on-campus crimes reported per 10,000 FTE students that enrolled in 2021. To include some examples that are closer to home, in the UPRM, 81 reports were filed from January [2023](https://www.uprm.edu/calidaddevida/informe-de-actos-delictivos-2022-2/) (47 in 2023) to August [2024](https://www.uprm.edu/calidaddevida/informe-de-actos-delictivos-2022-2-2/) (34 in 2024 so far). These reports ranged from: theft of campus property ([a TV Sharp TV 70” was reported stolen in January 2024](https://www.uprm.edu/calidaddevida/wp-content/uploads/sites/11/2024/04/Informe-de-Actos-Delictivos-enero-2024.pdf)), to violence on campus grounds ([a student was thrown against a chair by another student in February 2024](https://www.uprm.edu/calidaddevida/wp-content/uploads/sites/11/2024/04/Informe-de-Actos-Delictivos-febrero-2024-eom.pdf)), to verbal harassment and threats ([a student reported that she was being threatened by an employee in april, 2024](https://www.uprm.edu/calidaddevida/wp-content/uploads/sites/11/2024/06/Informe-de-Actos-Delictivos-ABRIL-2024-.pdf)).

For this reason, we have structured the domain of our application, SafeRUM, around college safety, as we can see an opportunity to provide the people of the UPRM a service that can provide them with a sense of security. With SafeRUM, there is an opportunity to provide quick and easy access to services that can help the people of the UPRM with tools that can help make our campus a safer place. The ability to generate reports can allow users to post detailed forms that communicate a particular situation that can compromise the safety of our students, informationing other users and staff members of something that they should be aware of. In the case of immediate danger, the ability of sending out a quick SOS report can reduce the time it takes to provide aid and safety, without having to run the risk that other alternatives like phone calls entail (like noise in a situation where remaining silent is critical.). Finally, granting the ability to share rumors among users would help those at the UPRM stay informed and on the lookout for potential threats, as well as inform admins of dangers that lurk around campus.

**Comment by Chosen-Juan1** [comment]
this rough sketch presents a more elevated sense of abstraction and is more rough around the edges (as the professor suggested).
