### ISSUE TITLE
[Lecture Topic Task] Document Invariants

### ISSUE THREAD

**Issue by lex939** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#267]
**Objective:**

Document at least one non-trivial invariant of an aggregate, explaining where the invariant might be temporarily violated and how and where it is reestablished to maintain consistency within the aggregate.

---

**Task Description:**

This task involves documenting the role of invariants within aggregates. An invariant is a condition that must hold true across all operations within the aggregate to maintain consistency. The documentation should:
- Clearly define the invariant(s) for the aggregate.
- Explain scenarios where the invariant might be violated temporarily due to operations.
- Describe how and where the invariant is restored to ensure the aggregate remains valid.

---

**Implementation:**

1. **Define the Aggregate Invariant:**
   - Clearly state at least one non-trivial invariant within an aggregate. This invariant should represent a rule or condition that must always be true for the aggregate to be consistent.

2. **Explain Temporary Violations:**
   - Identify any situations where the invariant may be temporarily violated during an operation or transaction.
   - Provide examples of specific operations that might cause the invariant to be momentarily broken.

3. **Describe Reestablishment of the Invariant:**
   - Explain how the invariant is reestablished after temporary violations. This should include descriptions of mechanisms or logic within the aggregate that ensure the invariant is restored after operations are completed.

4. **Illustrate with Examples:**
   - Include one or more practical examples of how the invariant works within the aggregate.
   - Show how the aggregate temporarily violates and then reestablishes the invariant in a real scenario.

---

**Subtasks:**

1. **Document the Aggregate Invariant:**
   - Identify and clearly state the invariant that must be maintained in the aggregate.
   
2. **Identify Temporary Violations:**
   - Document scenarios or operations where the invariant might be temporarily violated during the aggregate’s lifecycle.

3. **Describe How the Invariant Is Reestablished:**
   - Provide details on how the aggregate ensures that the invariant is restored after it is temporarily violated.

4. **Provide Examples:**
   - Include practical examples with code snippets showing how the invariant is managed within the aggregate.

---

**Testing and Debugging:**

After documenting the invariant:
- Verify that the invariant is clearly defined and is non-trivial.
- Ensure the explanation of temporary violations and their reestablishment is coherent and aligned with the aggregate’s operations.
- Review examples to confirm they accurately illustrate how the invariant is maintained and restored.

---

**Deadline:**

Complete the task by **Monday, October 21, 2024, at 11:00 PM (23:00)**, in alignment with the week of the Milestone 2 deadline.

**Comment by Chosen-Juan1** [comment]
Invariants are conditions that need to remain constant during operations that utilize the aggregate they belong to. In the report aggregate, several invariant conditions must remain true when being operated on. Things like a report's title and label must remain constant in order to fulfill the invariant conditions, like being sent to the report's list once it has been created and being displayed on said list after it's creation. This condition, however, is temporarily violated during the aggregate's creation process, as a report is assigned temporary values while the user fills in the required information, temporarily breaking the invariant condition of having immutable fields. Once the user finishes, these values change and are set as the new values, restoring the invariant condition to the aggregate.

**Comment by Chosen-Juan1** [comment]
Sadly, I can't provide screenshots of the program since the application refuses to load on my computer. However, I can provide examples of code where a temporary value is assigned and then changed to the user's input.
<img width="420" alt="screenshot_of_invariant_example" src="https://github.com/user-attachments/assets/81611ca4-2986-484d-9532-3d5f4f7de955">
