### ISSUE TITLE
Documentation Feedback: Address and Differentiate

### ISSUE THREAD

**Issue by lex939** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#381]
1. Address Data Consistency in Incident Report Aggregate

    Feedback: "Your discussion of the incident report aggregate leaves some questions. For example, how are user details dealt with? Say, an incident report was filed by user A, what if user A drops their account right after filing the report? Or, if an incident gets deleted, are the user details also deleted? What if the user reported other incidents? These are all not difficult to answer and they are exactly what the aggregate should answer."

    Task: Revisit the incident report aggregate to address how user details are managed, especially when users delete accounts or incidents are removed. Ensure data consistency and integrity.

2. Differentiate Between Application and Domain Layers

    Feedback: "There's a difference between the application layer and the domain layer. The domain layer should have the business logic and the application layer should have all those aspects that are only necessary because we have decided to create this as an app i.e., they do not come from the business knowledge, but from administrative aspects introduced by our app."

    Task: Ensure the system design clearly separates the domain layer (business logic) from the application layer (app-specific functionalities).

Deadline by end of Milestone 3.

**Comment by johnsantiago9** [comment]
I made some updates to the Incident Report Aggregate based on the professor's feedback. Basically, I addressed data consistency issues related to users deleting their accounts and incidents being removed. Now, if a user deletes their account, their details in any reports they've submitted get anonymized instead of being deleted. This way, the reports remain intact for historical purposes, but we still respect the user's privacy. Also, when an incident is deleted, any media attachments linked to it are also removed, but the user's details stay unless all of their reports are deleted—in that case, we anonymize their info too. I also clarified how we handle user details when they're linked to multiple reports: we keep their info as long as they have other reports, and only anonymize it when there are no reports left. I added some new functions and improved the explanations to make sure everything stays consistent.
