### ISSUE TITLE
Documentation Feedback: Document Code Changes

### ISSUE THREAD

**Issue by lex939** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#382]
1. Consider Using Higher-Order Components Over Context API

    Feedback: "While the context API solves the problem of prop drilling, it comes with the drawback of creating a global state-based design. Consider using higher-order components, using functions to assemble components from other components."

    Task: Evaluate replacing the Context API with higher-order components to manage state more effectively and avoid a global state design. Document this.

2. Use Enums Instead of Strings for Report Types

    Feedback: "Instead of using strings to distinguish between the different kinds of reports that the factory can create, consider using enums https://docs.python.org/3/howto/enum.html#enum-basic-tutorial"

    Task: Implement enums to represent different report types in the factory pattern, enhancing code readability and reducing errors. Document this.

Deadline by end of Milestone 3.

**Comment by CaribbeanCool** [comment]
@lex939 Below is the documentation feedback:

# Consider Using Higher-Order Components Over Context API
While the Context API helps with prop drilling, it can lead to a global state design, which isn’t always ideal. To manage state more effectively, it is recommended to use Higher-Order Components (HOCs) instead. HOCs are functions that take a component and return a new one with extra props, making components more reusable and easier to test. For instance, rather than using the Context API to provide user data, a HOC can be created to inject this data into the component. This approach avoids a global state design and improves the separation of concerns. Additionally, using HOCs enhances component reusability and testability. Below is an example of `Signup.tsx` after using HOC:
```
import React from 'react';

function withUser(Component) {
  return function WrappedComponent(props) {
    const user = { name: 'John Doe' }; // Example user data
    return <Component {...props} user={user} />;
  };
}

function UserProfile({ user }) {
  return <div>{user.name}</div>;
}

export default withUser(UserProfile);
```

# Use Enums Instead of Strings for Report Types
Using strings to differentiate report types can cause errors and make the code harder to read. Instead, it is advisable to use enums. Enums allow defining a set of named values, which makes the code clearer and reduces mistakes. For example, replacing string literals with enums to represent report types in the project will enhance code readability, lower the risk of typos, and provide a more maintainable way to handle report types. Implementing enums for report types and updating the factory pattern and related code accordingly will improve both state management and code quality in the project. The code const `reportType = 'Report';` can be transformed with enums as shown below:
```
enum ReportType {
  Report = 'Report',
  SOS = 'SOS',
}
const reportType = ReportType.Report;
```
By following these recommendations, the project will benefit from improved state management, enhanced code readability, and reduced likelihood of errors.

**Comment by lex939** [comment]
Please place in the Google Document file in the section it fits best and reply to this comment with where you placed it. Thanks.
