### ISSUE TITLE
Documentation Feedback: Review and Update App Layer Components

### ISSUE THREAD

**Issue by lex939** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#390]
Review and Update Application Layer Components

    Feedback: "There's a difference between the application layer and the domain layer. The application layer should have all those aspects that are only necessary because we have decided to create this as an app i.e., they do not come from the business knowledge, but from administrative aspects introduced by our app."

    Task: Audit the application layer components to ensure they only contain app-specific functionalities and not business logic. Document this.

Deadline by end of Milestone 3.

**Comment by diego-velez-upr** [comment]
I fear that the feedback presented for this task is incomplete, the full quote is:
> There's a difference between the application layer and the domain layer. The domain layer should have the business logic and the application layer should have all those aspects that are only necessary because we have decided to create this as an app i.e. they do not come from the business knowledge, but from administrative aspects introduced by our app.

One half of the feedback is expected to be addressed in this issue, while the other seems to be expected to be addressed in #381. I believe that the full feedback should be addressed in **one** issue otherwise it is very likely for the same problem to happen again, where we have a difference between layers when there shouldn't.

I don't have a problem with addressing the full feedback as a part of this task.

@YanehRuiz what do you think?

**Comment by diego-velez-upr** [comment]
I addressed the task as it was originally described in the issue. I changed what the responsibilities of the `Application/Service Layer` are in the `2.3 Implementation` section.

**Comment by YanehRuiz** [comment]
Tagging @lex939 to cross check

**Comment by lex939** [comment]
It's been fixed! Thank you ☺️
